### ISSUE TITLE
cannot reproduce the MAE result

### ISSUE THREAD

**Issue by youyou0988** [paplhjak/Facial-Age-Estimation-Benchmark#14]
MAE result of UTKFace in readme  is 4.38 using Baseline Cross-Entropy.
But I train model using command `python3 train.py facebase/configs/UTKFace_256x256.yaml 0[1,2,3,4] --wandb-disabled`, MAE result is 9.48 in valid.
the training data is UTKFace only.
I want to know what training data should I use if I want to get 4.38 as readme.

**Comment by youyou0988** [comment]
The email has been sent, thank you so much.

**Comment by paplhjak** [comment]
Please note that no such email has been received as of yet.

**Comment by youyou0988** [comment]
Is this address correct? `paplhjak@fel.cvut.cz`

my email address is `yu_yang8909@163.com`

Could you please send me the pre-trained model ?

**Comment by paplhjak** [comment]
The file has been sent to the provided email. Please, let us know whether you received it.

**Comment by 20193939** [comment]
Hello, I am also very interested in your article, could you please send me the pre-trained model on IMDB-WIKI mentioned above? Thank you very much! My email:2301388@stu.neu.edu.cn

**Comment by youyou0988** [comment]
The model has been received, thanks.

**Comment by 20193939** [comment]
> The model has been received, thanks.

Could you please share the model with me? thank you.

**Comment by paplhjak** [comment]
> > The model has been received, thanks.
> 
> Could you please share the model with me? thank you.

Please, send an email to paplhjak@fel.cvut.cz. We will forward the model to you.
