### ISSUE TITLE
Provide a pytorch checkpoints for IMDB-Wiki 

### ISSUE THREAD

**Issue by YaelGrins** [paplhjak/Facial-Age-Estimation-Benchmark#18]
Hi, 
Thanks for you contribution. 
Could you please provide the PyTorch checkpoint for a backbone pre-trained on the IMDB-WIKI dataset?
Thanks in advance, 
Yael

**Comment by paplhjak** [comment]
I will look into it.

**Comment by paplhjak** [comment]
The backbone will be available by the end of the week.

**Comment by paplhjak** [comment]
Please, find the checkpoint at [this link](https://paplham.cloud/index.php/s/BBmBFzwz32ccxsi)

**Comment by paplhjak** [comment]
In case you prefer the JIT scripted model, please use the following [link](https://paplham.cloud/index.php/s/TmtPyz4ABkYkL7E)
