### ISSUE TITLE
Missing config files for different head/loss methods

### ISSUE THREAD

**Issue by caiopetruccirosa** [paplhjak/Facial-Age-Estimation-Benchmark#21]
Hi @paplhjak! Thanks for adding more config files on #20!

However, I noticed that, on `facebase/configs`, only the config files for the different weight initialization strategies of the baseline ResNet50 with a Cross-Entropy loss head experiments were added.

Could you also provide the config files for the other methods reported as implemented and evaluated in the paper, such as `Regression`, `OR-CNN`, `DLDL`, `DLDL-v2`, `SORD`, `Mean-Var`, `Unimodal`, and `FaRL + MLP`?

That would be greatly appreciated, as I am trying to reproduce all the results reported in the paper.

**Comment by caiopetruccirosa** [comment]
Hi @paplhjak!

Thanks again for the support. :)

Just wanted to follow up on my previous request regarding the config files for the additional methods (`Regression`, `OR-CNN`, `DLDL`, `DLDL-v2`, `SORD`, `Mean-Var`, `Unimodal`, and `FaRL + MLP`). If you could provide these, it would be a great help in completing the reproduction of the results from the paper.

**Comment by paplhjak** [comment]
Looking at it more closely, the FaRL configuration file is not there - I will add it

**Comment by jvdrag** [comment]
can you add the FaRL + MLP ?

**Comment by zdaiot** [comment]
@paplhjak can you add the FaRL + MLP
